"""initial_schema

Revision ID: 698950a6d6d2
Revises: 
Create Date: 2026-06-15 14:52:41.313806

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy import JSON

# revision identifiers, used by Alembic.
revision: str = '698950a6d6d2'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('model_pricing',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('provider', sa.String(length=64), nullable=False),
    sa.Column('model_id', sa.String(length=128), nullable=False),
    sa.Column('input_per_1m', sa.Numeric(precision=10, scale=4), nullable=False),
    sa.Column('output_per_1m', sa.Numeric(precision=10, scale=4), nullable=False),
    sa.Column('currency', sa.String(length=8), nullable=False),
    sa.Column('source', sa.String(length=255), nullable=True),
    sa.Column('last_updated', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('note', sa.String(length=500), nullable=True),
    sa.Column('is_default', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('provider', 'model_id', name='uq_pricing_provider_model')
    )
    with op.batch_alter_table('model_pricing', schema=None) as batch_op:
        batch_op.create_index('idx_pricing_provider_default', ['provider', 'is_default'], unique=False)
        batch_op.create_index(batch_op.f('ix_model_pricing_provider'), ['provider'], unique=False)

    op.create_table('projects',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('mode', sa.String(length=32), nullable=False),
    sa.Column('category', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('closed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completion_report', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.create_index('idx_projects_category', ['category'], unique=False)
        batch_op.create_index('idx_projects_created_at', ['created_at'], unique=False)
        batch_op.create_index('idx_projects_mode', ['mode'], unique=False)
        batch_op.create_index('idx_projects_status', ['status'], unique=False)

    op.create_table('roles',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('role_type', sa.String(length=32), nullable=False),
    sa.Column('provider', sa.String(length=64), nullable=True),
    sa.Column('model', sa.String(length=128), nullable=True),
    sa.Column('system_prompt', sa.Text(), nullable=True),
    sa.Column('tool_whitelist', sa.JSON(), nullable=True),
    sa.Column('timeout_sec', sa.Integer(), nullable=False),
    sa.Column('fresh_context', sa.Boolean(), nullable=False),
    sa.Column('estimated_savings_usd', sa.Numeric(precision=10, scale=4), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('roles', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_roles_name'), ['name'], unique=True)

    op.create_table('tasks',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('project_id', sa.String(length=32), nullable=True),
    sa.Column('parent_id', sa.String(length=32), nullable=True),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('category', sa.String(length=32), nullable=False),
    sa.Column('assigned_role', sa.String(length=64), nullable=True),
    sa.Column('assigned_subagent', sa.String(length=64), nullable=True),
    sa.Column('iteration_count', sa.Integer(), nullable=False),
    sa.Column('order', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('claimed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('emergency', sa.Boolean(), nullable=False),
    sa.Column('pricing_snapshot', sa.JSON(), nullable=True),
    sa.Column('tags', sa.JSON(), nullable=True),
    sa.Column('success_criteria', sa.JSON(), nullable=True),
    sa.Column('meta', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['parent_id'], ['tasks.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.create_index('idx_tasks_assigned_role', ['assigned_role'], unique=False)
        batch_op.create_index('idx_tasks_created_at_desc', ['created_at'], unique=False)
        batch_op.create_index('idx_tasks_emergency', ['emergency'], unique=False)
        batch_op.create_index('idx_tasks_parent_id', ['parent_id'], unique=False)
        batch_op.create_index('idx_tasks_priority_desc', ['priority'], unique=False)
        batch_op.create_index('idx_tasks_project_id', ['project_id'], unique=False)
        batch_op.create_index('idx_tasks_project_status', ['project_id', 'status'], unique=False)
        batch_op.create_index('idx_tasks_status', ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_tasks_status'), ['status'], unique=False)

    op.create_table('task_history',
    sa.Column('id', sa.BigInteger().with_variant(sa.INTEGER(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('task_id', sa.String(length=32), nullable=False),
    sa.Column('ts', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('event', sa.String(length=64), nullable=False),
    sa.Column('agent', sa.String(length=64), nullable=True),
    sa.Column('model', sa.String(length=128), nullable=True),
    sa.Column('tokens_in', sa.Integer(), nullable=False),
    sa.Column('tokens_out', sa.Integer(), nullable=False),
    sa.Column('cost_usd', sa.Numeric(precision=12, scale=6), nullable=False),
    sa.Column('details', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('task_history', schema=None) as batch_op:
        batch_op.create_index('idx_history_agent', ['agent'], unique=False)
        batch_op.create_index('idx_history_event', ['event'], unique=False)
        batch_op.create_index('idx_history_model', ['model'], unique=False)
        batch_op.create_index('idx_history_task_ts', ['task_id', 'ts'], unique=False)
        batch_op.create_index('idx_history_ts_desc', ['ts'], unique=False)
        batch_op.create_index(batch_op.f('ix_task_history_agent'), ['agent'], unique=False)
        batch_op.create_index(batch_op.f('ix_task_history_event'), ['event'], unique=False)

    op.create_table('token_usage',
    sa.Column('id', sa.BigInteger().with_variant(sa.INTEGER(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('task_id', sa.String(length=32), nullable=True),
    sa.Column('history_id', sa.BigInteger().with_variant(sa.INTEGER(), 'sqlite'), nullable=True),
    sa.Column('model', sa.String(length=128), nullable=False),
    sa.Column('provider', sa.String(length=64), nullable=False),
    sa.Column('role', sa.String(length=64), nullable=True),
    sa.Column('tokens_in', sa.Integer(), nullable=False),
    sa.Column('tokens_out', sa.Integer(), nullable=False),
    sa.Column('cost_usd', sa.Numeric(precision=12, scale=6), nullable=False),
    sa.Column('input_per_1m', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('output_per_1m', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('pricing_source', sa.String(length=255), nullable=True),
    sa.Column('snapshot_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('recorded_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['history_id'], ['task_history.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('token_usage', schema=None) as batch_op:
        batch_op.create_index('idx_token_model', ['model'], unique=False)
        batch_op.create_index('idx_token_provider', ['provider'], unique=False)
        batch_op.create_index('idx_token_recorded_at_desc', ['recorded_at'], unique=False)
        batch_op.create_index('idx_token_role', ['role'], unique=False)
        batch_op.create_index('idx_token_task_id', ['task_id'], unique=False)
        batch_op.create_index('idx_token_task_recorded', ['task_id', 'recorded_at'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('token_usage', schema=None) as batch_op:
        batch_op.drop_index('idx_token_task_recorded')
        batch_op.drop_index('idx_token_task_id')
        batch_op.drop_index('idx_token_role')
        batch_op.drop_index('idx_token_recorded_at_desc')
        batch_op.drop_index('idx_token_provider')
        batch_op.drop_index('idx_token_model')

    op.drop_table('token_usage')
    with op.batch_alter_table('task_history', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_task_history_event'))
        batch_op.drop_index(batch_op.f('ix_task_history_agent'))
        batch_op.drop_index('idx_history_ts_desc')
        batch_op.drop_index('idx_history_task_ts')
        batch_op.drop_index('idx_history_model')
        batch_op.drop_index('idx_history_event')
        batch_op.drop_index('idx_history_agent')

    op.drop_table('task_history')
    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_tasks_status'))
        batch_op.drop_index('idx_tasks_status')
        batch_op.drop_index('idx_tasks_project_status')
        batch_op.drop_index('idx_tasks_project_id')
        batch_op.drop_index('idx_tasks_priority_desc')
        batch_op.drop_index('idx_tasks_parent_id')
        batch_op.drop_index('idx_tasks_emergency')
        batch_op.drop_index('idx_tasks_created_at_desc')
        batch_op.drop_index('idx_tasks_assigned_role')

    op.drop_table('tasks')
    with op.batch_alter_table('roles', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_roles_name'))

    op.drop_table('roles')
    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.drop_index('idx_projects_status')
        batch_op.drop_index('idx_projects_mode')
        batch_op.drop_index('idx_projects_created_at')
        batch_op.drop_index('idx_projects_category')

    op.drop_table('projects')
    with op.batch_alter_table('model_pricing', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_model_pricing_provider'))
        batch_op.drop_index('idx_pricing_provider_default')

    op.drop_table('model_pricing')
    # ### end Alembic commands ###
