"""add_brainstorm_requirement_review_implementation

Revision ID: f05c21f4e9e7
Revises: 698950a6d6d2
Create Date: 2026-06-15 15:23:10.819911

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy import JSON
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision: str = 'f05c21f4e9e7'
down_revision: Union[str, Sequence[str], None] = '698950a6d6d2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('brainstorm_entries',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('project_id', sa.String(length=32), nullable=False),
    sa.Column('role', sa.String(length=16), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('phase', sa.String(length=32), nullable=False),
    sa.Column('ts', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('brainstorm_entries', schema=None) as batch_op:
        batch_op.create_index('idx_brainstorm_project', ['project_id'], unique=False)
        batch_op.create_index('idx_brainstorm_ts', ['ts'], unique=False)

    op.create_table('implementation_steps',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('project_id', sa.String(length=32), nullable=False),
    sa.Column('phase', sa.Integer(), nullable=False),
    sa.Column('step_index', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('cio_approved', sa.Boolean(), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('implementation_steps', schema=None) as batch_op:
        batch_op.create_index('idx_impl_phase', ['phase'], unique=False)
        batch_op.create_index('idx_impl_project', ['project_id'], unique=False)

    op.create_table('requirement_docs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('project_id', sa.String(length=32), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('markdown', sa.Text(), nullable=False),
    sa.Column('review_score', sa.Float(), nullable=True),
    sa.Column('review_notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('requirement_docs', schema=None) as batch_op:
        batch_op.create_index('idx_reqdoc_project', ['project_id'], unique=False)
        batch_op.create_index('idx_reqdoc_status', ['status'], unique=False)

    op.create_table('review_pipelines',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('project_id', sa.String(length=32), nullable=False),
    sa.Column('doc_id', sa.Integer(), nullable=True),
    sa.Column('step_name', sa.String(length=64), nullable=False),
    sa.Column('step_index', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('result', sa.Text(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['doc_id'], ['requirement_docs.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('review_pipelines', schema=None) as batch_op:
        batch_op.create_index('idx_review_project', ['project_id'], unique=False)
        batch_op.create_index('idx_review_status', ['status'], unique=False)

    with op.batch_alter_table('roles', schema=None) as batch_op:
        batch_op.alter_column('tool_whitelist',
               existing_type=sqlite.JSON(),
               type_=sa.JSON(),
               existing_nullable=True)

    with op.batch_alter_table('task_history', schema=None) as batch_op:
        batch_op.alter_column('details',
               existing_type=sqlite.JSON(),
               type_=sa.JSON(),
               existing_nullable=True)

    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.alter_column('pricing_snapshot',
               existing_type=sqlite.JSON(),
               type_=sa.JSON(),
               existing_nullable=True)
        batch_op.alter_column('tags',
               existing_type=sqlite.JSON(),
               type_=sa.JSON(),
               existing_nullable=True)
        batch_op.alter_column('success_criteria',
               existing_type=sqlite.JSON(),
               type_=sa.JSON(),
               existing_nullable=True)
        batch_op.alter_column('meta',
               existing_type=sqlite.JSON(),
               type_=sa.JSON(),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.alter_column('meta',
               existing_type=sa.JSON(),
               type_=sqlite.JSON(),
               existing_nullable=True)
        batch_op.alter_column('success_criteria',
               existing_type=sa.JSON(),
               type_=sqlite.JSON(),
               existing_nullable=True)
        batch_op.alter_column('tags',
               existing_type=sa.JSON(),
               type_=sqlite.JSON(),
               existing_nullable=True)
        batch_op.alter_column('pricing_snapshot',
               existing_type=sa.JSON(),
               type_=sqlite.JSON(),
               existing_nullable=True)

    with op.batch_alter_table('task_history', schema=None) as batch_op:
        batch_op.alter_column('details',
               existing_type=sa.JSON(),
               type_=sqlite.JSON(),
               existing_nullable=True)

    with op.batch_alter_table('roles', schema=None) as batch_op:
        batch_op.alter_column('tool_whitelist',
               existing_type=sa.JSON(),
               type_=sqlite.JSON(),
               existing_nullable=True)

    with op.batch_alter_table('review_pipelines', schema=None) as batch_op:
        batch_op.drop_index('idx_review_status')
        batch_op.drop_index('idx_review_project')

    op.drop_table('review_pipelines')
    with op.batch_alter_table('requirement_docs', schema=None) as batch_op:
        batch_op.drop_index('idx_reqdoc_status')
        batch_op.drop_index('idx_reqdoc_project')

    op.drop_table('requirement_docs')
    with op.batch_alter_table('implementation_steps', schema=None) as batch_op:
        batch_op.drop_index('idx_impl_project')
        batch_op.drop_index('idx_impl_phase')

    op.drop_table('implementation_steps')
    with op.batch_alter_table('brainstorm_entries', schema=None) as batch_op:
        batch_op.drop_index('idx_brainstorm_ts')
        batch_op.drop_index('idx_brainstorm_project')

    op.drop_table('brainstorm_entries')
    # ### end Alembic commands ###
